framework:
    default_locale: hu
    enabled_locales: ['hu', 'en']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - hu
        providers:
        paths:
            - '%kernel.project_dir%/translations/hu'
            - '%kernel.project_dir%/translations/en'
