services:
  php:
    depends_on:
      - db
    build:
      dockerfile: ./docker/php/Dockerfile
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-localhost}|php$$
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    links:
      - db
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    volumes:
      - ./:/app
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Europe/Budapest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  mailpit:
    image: axllent/mailpit
    environment:
      TZ: Europe/Budapest
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    logging:
      driver: none
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
